### PR TITLE
chore: Add commitlint to enforce CONTRIBUTING guidelines.

### PR DESCRIPTION
**Pull request by infiniteluke**
This PR introduces enforcing the [Conventional Commits Specification](https://conventionalcommits.org/) on commit. Specifically the angular convention that inspired the spec.

Current rules included (obviously up for review and/or customization):
- [@commitlint/config-angular](https://github.com/marionebl/commitlint/blob/master/@commitlint/config-angular) which enforces common "types", casing, length rules etc..
- [@commitlint/config-lerna-scopes](https://github.com/marionebl/commitlint/blob/master/@commitlint/config-lerna-scopes) which ensures the "scope" portion is one of the lerna packages. generic commits would have no scope like `chore: do something generic`:
lerna packages enforced in commit scope
 
Also included is [running these on Travis](https://travis-ci.org/emdaer/emdaer/builds/290870803#L463) since people can always `--no-verify`

### CODE REVIEW

**Comment by flipactual** [comment]
This is better

**Review by flipactual — CHANGES_REQUESTED** [review]
Can you please update CONTRIBUTING to reflect these specific conventions?

**Comment by flipactual** [comment]
Also I'm not sure it's working

A commit message of `ayy lmao` worked for me – can we enforce having types?

**Comment by infiniteluke** [comment]
Closing because I broke this PR by messing with history 🤦‍♂️

**Pull request closed without merging**
