### PR TITLE
Fix code block syntax highlighting

### PR DESCRIPTION
**Pull request by infiniteluke**
**What**:
"ignore" code fences when running marked

**Why**:
This allows platforms to render syntax highlighting how they please.

**How**:
This involved creating a custom marked code renderer that wraps any code fence that contains a language in a special comment. Plain code fences are wrapped in pre/code like usual. After emdaer runs it's plugins and transforms and minifies html, it "uncomments" the code fences.

NOTE: This also involved removing the `removeComments` options on HTML minifier. This is why you'll see those added in the READMEs below.

**Checklist**:

- [x] ~Documentation~
- [x] Tests
- [x] Ready to be merged 
- [x] Added myself to AUTHORS 

This is not ready to be merged. I am struggling to get this applied to the emdaer repo. I think between all of the `@emdaer/core` deps through the plugins/transforms and then the devDep on the `file:` in the main repo, I’m missing something. However, when I link into other projects things are working great.

### CODE REVIEW

**Comment by infiniteluke** [comment]
Should also note that this sacrifices portability a bit. If pure HTML is needed, code fences should be used without the language specifier. Will document that before merging.

**Comment by infiniteluke** [comment]
Check out https://github.com/emdaer/emdaer/blob/6b2be619895a8cdb84f245abfc0dbdca543cb5de/README.md

**Review by flipactual — APPROVED** [review]
lgtm

**Comment by infiniteluke** [comment]
Doing further functional testing before we merge.

**Comment by infiniteluke** [comment]
Cool. I couldn't break it.

**Pull request merged**
