### PR TITLE
add plugin for adding tables (fixes #13)

### LINKED ISSUE #13: Need plugin for adding tables

### PR DESCRIPTION
**Pull request by flipactual**

### CODE REVIEW

**Comment by flipactual** [comment]
Got any plugins that return a matrix?

**Comment by infiniteluke** [comment]
I mean a given cell. what if we want to create a table full of images, like a potential contributors plugin. I suppose this would require each cell to be a table cell plugin. May be overkill for now.

**Comment by flipactual** [comment]
I don't believe we don't have any plugins that return tabular data (or data that could be constructed into tabular data)

**Comment by flipactual** [comment]
And maybe `emdaer-util-*` should be considered for things that are currently plugins (like value-from-package). Probably even. But if we want to get that in for v1.0.0, we'll need to reconsider the general scope and launch target

**Comment by infiniteluke** [comment]
I don't think this should block 1.0.0

**Pull request merged**
