### PR TITLE
Initial AST work

### PR DESCRIPTION
**Pull request by flipactual**
Sets up tests for AST flag

### CODE REVIEW

**Comment by flipactual** [comment]
I'm having to sort out some feature flag stuff as I go here – eef31f8 allows us to override flags in place so that there's a consistent single source of truth

**Comment by flipactual** [comment]
Getting an error from `cli` I'm having trouble tracking down
```
 FAIL  packages/cli/src/index.test.js
  ● Test suite failed to run

    TypeError: inherits is not a function

      at Object.<anonymous> (packages/cli/node_modules/@emdaer/core/node_modules/parse5/lib/extensions/position_tracking/preprocessor_mixin.js:29:1)
      at Object.<anonymous> (packages/cli/node_modules/@emdaer/core/node_modules/parse5/lib/extensions/location_info/tokenizer_mixin.js:5:41)
      at Object.<anonymous> (packages/cli/node_modules/@emdaer/core/node_modules/parse5/lib/extensions/location_info/parser_mixin.js:5:34)
```

---

Also, minor detail, this breaks a lot of stuff

**Comment by infiniteluke** [comment]
Was able to reproduce issue. Will investigate more soon

**Review by infiniteluke — APPROVED** [review]

**Comment by infiniteluke** [comment]
With the flag enabled, transform-table-of-contents breaks because it relies on `<!--- toc -->`. A future version of transform-table-of-contents will be made that does not use the above once we unify emdaer's transform/plugin syntax.

**Comment by flipactual** [comment]
@infiniteluke I think I'm going to merge the flags for AST and common comment into a single initiative before proceeding – thoughts?

**Review by infiniteluke — APPROVED** [review]

**Comment by infiniteluke** [comment]
Sounds good.

**Pull request merged**
